### ISSUE TITLE
Integrate Position Control with PID into the Storage Talon

### ISSUE THREAD

**Issue by joecaraccio** [Team138Entropy/Entropy2020#119]
Right now the Talon and encoder on intake system is controlled via the roborio. We should change control of it to the talon:

- If we are rotating a set amount of on every trigger, the logic could be less breakable if we are polling for our position set point and incrementing it
- No latency concerns from the rest of the code base, the talons firmware is handling when we reach the distance. Much less likely of an overshoot
- PID controlling will allow us to get very precise with our desired position. We are going to want to be able to intake FAST and tightly.

We will already have the code to do this for the turret, so we should implement this for the storage as well. 

Max - You've got a lot on your plate so I also assigned Daniel to help with this. It would be good for him to learn how position mode on the talons works.

**Comment by maxh65000** [comment]
Done
