### ISSUE TITLE
Integrate subsystems that were independently developed

### ISSUE THREAD

**Issue by Barrelwolf38087** [Team138Entropy/Entropy2020#13]
- [x] Create Robot State machine to integrate:
- [x] Shooter + Turret
- [x] Shooter + Vision
- [x] Shooter + Storage
- [x] Intake + Storage
- [x] Bind controls

**Comment by jhinspeter** [comment]
![image](https://drive.google.com/uc?id=1F0ss2SMFkRYL4uQu-HnfwC-71SM-qQbZ)

**Comment by maxh65000** [comment]
What does "bind controls" mean? Does it mean to set up the controls for the subsystems?

**Comment by joecaraccio** [comment]
button press -> desired robot action basically.

Obviously a lot more complicated than that, but thats kinda happening as we go
