### ISSUE TITLE
Add Boolean for practice vs comp bot

### ISSUE THREAD

**Issue by maxh65000** [Team138Entropy/Entropy2020#140]
We did this last year and it was pretty simple. Maybe a singleton subsystem that has a getPracticeBot() method? It's digital input 0 anyway.

- [x] add method call / boolean / whatever to read the digital input
- [x] integrate this with the speed lookup table
- [x] integrate this with storage encoder distance
- [x] integrate this with the storage encoder measurement factors (the encoder is on different storage sides on different parts)

**Comment by maxh65000** [comment]
@onedeadeye @averwhy are you interested in doing this?

**Comment by Barrelwolf38087** [comment]
I'd suggest using a static method on Robot rather than a whole singleton class for this. Lazy initialization is kind of pointless here.
