### ISSUE TITLE
Add toggle to enable/disable LED rings

### ISSUE THREAD

**Issue by maxh65000** [Team138Entropy/Entropy2020#33]
- [x] interface with the LED with software
- [x] make it a button

**Comment by maxh65000** [comment]
@Nick-P-Orr we're gonna do this with the operator trigger, right?

**Comment by Nick-P-Orr** [comment]
Yeah, when the "aim" button (I believe left trigger as of now) is pressed, turn the spike relay on. I don't intend to do individual control of the rings anymore - just always turn both on.

**Comment by joecaraccio** [comment]
If you look at the AlternateStateMachine branch,

when auto aim is enabled the LED should come up.
We also plan to be in Auto Aim by default though (and ideally our vision is good enough that we never leave) so we will need to add a check for that state in RobotInit
