### ISSUE TITLE
Add JavaDoc

### ISSUE THREAD

**Issue by maxh65000** [Team138Entropy/Entropy2020#54]
Adding javadoc to more stuff would be good

**Comment by joecaraccio** [comment]
Lets spend time on the actual robot....

**Comment by maxh65000** [comment]
Not everyone can be constantly working on the robot especially earlier in the season. Adding documentation is something you can do if you're waiting for something else

**Comment by Barrelwolf38087** [comment]
Agreed, and @averwhy doesn't really have much else to work on.

**Comment by joecaraccio** [comment]
There is plenty more exciting work for @averwhy to get involved with than just documentation

**Comment by joecaraccio** [comment]
I'll talk to him tonight

**Comment by maxh65000** [comment]
Sounds good

**Comment by joecaraccio** [comment]
I don't disagree with you guys that documentation is important.. I just think we can find more exciting things that are equally as beneficial.. if not more!
