### ISSUE TITLE
Add driver view cameras

### ISSUE THREAD

**Issue by maxh65000** [Team138Entropy/Entropy2020#60]
These are the camera(s) that allow the drive team to see what's happening (not the automatic controls). You should be able to copy code from last year.

- [x] Add cameras to code
- [x] Add cameras to shuffleboard

**Comment by jmcgnh** [comment]
I've ordered 4 new Microsoft cameras, since we only have one working camera of this type at this time.

**Comment by maxh65000** [comment]
Epic
