### ISSUE TITLE
Shuffleboard VS Smartdashboard

### ISSUE THREAD

**Issue by joecaraccio** [Team138Entropy/Entropy2020#62]
So from my understanding.. shuffleboard is just a newer, improved smartdashboard? Only reason I ask is because I think some branches are using smart dashboard still. 

Should we convert all of those to shuffle board instead? tagging everyone just to make sure IF they are using the dashboard/shuffleboard they input their feedback

**Comment by maxh65000** [comment]
If I understand correctly, shuffleboard is controlled by SmartDashboard API calls.

**Comment by joecaraccio** [comment]
https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/shuffleboard/Shuffleboard.html

**Comment by onedeadeye** [comment]
AFAIK, we only would care about the discrepancy between SmartDashboard and Shiffleboard if we wanted to access a Shuffleboard-exclusive feature from code, e.g. setting the true/false color of a boolean display, in code. We were very inconsistent last year with this and ran into no issues. All beautification is typically done in the Shuffleboard's local configs, which we then save to master.

**Comment by joecaraccio** [comment]
Ah okay. Good to know. I'll close this. Thanks Liam
