### ISSUE TITLE
Tune encoder values

### ISSUE THREAD

**Issue by maxh65000** [Team138Entropy/Entropy2020#63]

**Comment by joecaraccio** [comment]
How is this done Max? We don't have the shooter encoder completely tuned or the drive encoders even mounted. Let's not git for the sake of git

**Comment by Nick-P-Orr** [comment]
Misunderstanding on my end, I thought the purpose of this issue was if we were reading encoder values from the talon at all and told Max we were all set, I didn't know this was meant to extend to the full implementation (tuning, mounting etc.).

**Comment by maxh65000** [comment]
I've tuned the shooter encoder for the practice bot in #100 but we will still need to tune for the comp bot

**Comment by maxh65000** [comment]
Duplicate of #73
