### ISSUE TITLE
Add stand-alone subsystem functions for HW debug

### ISSUE THREAD

**Issue by jhinspeter** [Team138Entropy/Entropy2020#69]
For each subsystem, add interfaces to control the motors and read the sensors
- [x] Intake
- [x] Storage
- [x] Shooter

**Comment by joecaraccio** [comment]
Think this is what you guys are doing anyways... but in our subsystem class there is a 'check subsystem' method that gets iterated through 1 at a time in test mode. Would be great for pit functionals!

**Comment by maxh65000** [comment]
I guess this is redundant now that we have the self test
