### ISSUE TITLE
Add Climber

### ISSUE THREAD

**Issue by Team138Entropy** [Team138Entropy/Entropy2020#8]

**Comment by joecaraccio** [comment]
@onedeadeye it is pretty probably going to be a week or two before we see the climbing system exist, but it is going to be a telescoping arm so to speak driven by motors. If that helps you think about placeholders at all... We will want to go forward and backward...

**Comment by jhinspeter** [comment]
![image](https://drive.google.com/uc?id=1cDhzs3GByOjG694QAjiHZNs5yUIAlnwf)
