### ISSUE TITLE
Integrate PID System with the new RobotTracker

### ISSUE THREAD

**Issue by joecaraccio** [Team138Entropy/Entropy2020#87]
Max, 

The new RobotTracker.java class (on the AlternateStatemachineConcept branch) has a method called 'GetTurretError(double timestamp)'

https://github.com/Team138Entropy/Entropy2020/blob/AlternateStatemachineConcept/src/main/java/frc/robot/RobotTracker.java

This method will return a Rotation2d object which you can then get degrees out of (or radians if you want). That degree value is the error to our targeted position... ie how far we want to move the turret.

I don't think RobotTracker will work immediately out of the gate (need to do some testing on it tomorrow night) but if you want to begin to develop a turret function (which I think you might already have) to adjust to that angle. 

In AutoAim mode from RobotLoop, we will constantly poll for the turret error, and then send it to the Turret subsystem to rotate accordingly. I think we might need a feedback function back to RobotTracker but I am not sure yet.

**Comment by maxh65000** [comment]
This is (mostly) done in the Turret branch.
