### ISSUE TITLE
Add Autonomous support

### ISSUE THREAD

**Issue by Team138Entropy** [Team138Entropy/Entropy2020#9]
- [x] Figure out WPILib's Kinematics/Odometry stuff
- [x] Create some system to allow autonomous control of the robot
- [x] Create framework for accurate autonomous movement (e.g. `void driveForward(Units.meters(2))`)
- [x] Create a "plan" to be run by the autonomous system that completes our autonomous mode objectives

**Comment by maxh65000** [comment]
This is essentially done, excepting some turning while moving stuff.
